### ISSUE TITLE
Return detailed member information for groups

### ISSUE THREAD

**Issue by D0nPiano** [yunity/foodsaving-backend#194]
Displaying a group, the frontend currently has to query through all member IDs in order to get all names. It'd be much simpler, if **/api/group/:id** could return:
- member.id
- member.display_name **or** first & last name
- member.photo (once photos are implemented)

/api/groups can still return just the member IDs; I don't think there is need for group member names & photos there.

**Comment by tiltec** [comment]
I'm strongly in favour of a shallow representation to keep the backend simple. Since we are using HTTP2, additional requests should be pretty cheap and can even be run in parallel.

So I would recommend to GET all member details separately. Or get *all* user details in one go.

**Comment by tiltec** [comment]
@Sneezoo - why is it strange for the frontend to do a request if it wants to get the detail of one object?
These things should be requested once in the frontend and then cached. But maybe I'm too strict about API purity and simplicity - maybe it's worth having two APIs: one for our frontend, and later one to interact with other services (like an App, or some open data approach).

This is nothing that needs to be _fixed_ in the backend, but rather a tradeoff between frontend and backend complexity. Backend complexity can introduce security bugs and data leaks, that's why I want to keep it simple (as I'm pretty inexperienced as web dev).
