### ISSUE TITLE
Implement Logging

### ISSUE THREAD

**Issue by alangecker** [yunity/foodsaving-backend#246]
I've collected a few requirements so far, but especially 5. needs a discussion!

### Requirements: _a log entry..._
1. should be translateable
2. can be caused by multipe users (i.e. pickup date)
3. can take place in different histories (a pickup log should be visible in the store AND in the group)
4. should be immutable (i.e. shop gets deleted)
5. should be hidden unless user has read access to one of the _scopes_

### Potential JSON Representation 
```json
{
  "scopes": [
    "group:3",
    "store:14",
    "user:13",
    "user:37"
  ],
  "translate": "STORE.PICKUP_LOG",
  "users": [13, 37],
  "payload":{
    "storeId":14,
    "storeName":"EDEKA Neuried",
  },
  "date":"2017-02-18T16:41:23.031Z"
}
```

**Comment by tiltec** [comment]
Good idea! This seems like a GET-only endpoint with extensive filter parameters. I'd change the following:

- use fields for all filter parameters instead of `scope`
- add `type` enum to mark action type (also as filter parameter)

```json
{
  "group": 3,
  "store": 14,
  "users": [13, 37],
  "type": "PICKUP_DONE"  // also "PICKUP_CREATED", "STORE_SETTING"...
  "payload":{ // different for each type
    "storeName": "EDEKA Neuried",
    "weight": "10",
    "comment": "many pomegrenades"
  },
}
```

Let's think a bit more about potential types.

- group is created
- group description/preview is changed
- group password is changed
- group address is changed
- user joins group
- user leaves group
- store is created
- store description is changed
- store address is changed
- store is deleted (not in frontend)
- single pickup date is created
- single pickup date is modified
- single pickup date is deleted
- regular pickup is created
- regular pickup is modified
- regular pickup is deleted
- single pickup in a series is modified
- pickup takes places
- pickup is created
- pickup is joined/left

**Comment by tiltec** [comment]
I started a backend implementation for this, will push soon!
