### ISSUE TITLE
Enable HTML mails (with plaintext alternative)

### ISSUE THREAD

**Issue by tiltec** [yunity/foodsaving-backend#292]
UPDATE:

We currently only send out text mails. There is one HTML template around, we should send it and create more. Be sure to also send plaintext alternative for non-HTML clients.

- [ ] add HTML content (see the code from @ShababShahriar below)
- [ ] tests

OLD CONTENT:

After signup or mail change: the mail "Verify your mail address" does contain only raw HTML code:

```
<html>
  <head>
    <title>WELCOME</title>
...
```
Instead, it should contain both the simple plain-text message (for clients who block HTML) and nicely rendered HTML.

(Also, if I only change my mail address or request the verification code again, I don't expect another "welcome" mail)

**Comment by tiltec** [comment]
@ShababShahriar do you maybe have time to investigate this?

**Comment by ShababShahriar** [comment]
I can't really spend much time on this now but here is perhaps all you need to know:

Users are getting "welcome" mail for different use cases because the `[send_verification_code](https://github.com/yunity/foodsaving-backend/blob/master/foodsaving/users/models.py#L109)` method is being called from three different places.

The solution to accommodate both plaintext and html messages is to have a plaintext message template which should be rendered as the `[body](https://github.com/yunity/foodsaving-backend/blob/master/foodsaving/users/models.py#L122)` and the `AnymailMessage` object should then call the method `attach_alternative` with the current html rendered content as its first parameter and `text/html` as the second one. More details can be found in the [Anymail docs](http://anymail.readthedocs.io/en/stable/sending/django_email/?highlight=attach_alternative).

The following example inspired from the [django docs](https://docs.djangoproject.com/en/1.11/topics/email/#sending-alternative-content-types) should make the implementation very easy:

```python
text_content = render_to_string('activation-mail-text.jinja', context)
msg = AnymailMessage(
            subject=render_to_string('mailverification-subject.jinja').replace('\n', ''),
            body=text_content,
            to=[self.unverified_email],
            from_email=settings.DEFAULT_FROM_EMAIL,
            track_clicks=False,
            track_opens=False
        )
html_content = render_to_string('activation-mail-html.jinja', context)
msg.attach_alternative(html_content, 'text/html)
msg.send()
```

**Comment by tiltec** [comment]
Thanks for the investigation! This should be helpful to future implementors...

I did the quick fix for now and switched back to text-only mails in #301 
I will rename this issue.
